openapi: 3.0.3
info:
  version: '1.0'
  title: 'Actors API Laravel'
  description: Lab6 PAB
servers:
  - description: Laravel
    url: http://localhost:8000/api
paths:
  /actors:
    get:
      tags:
        - actors
      summary: Returns paginated list of actors
      parameters:
        - in: query
          name: sort
          explode: false
          required: false
          style: form
          schema:
            type: array
            items:
              type: string
              example: height$ASC
            example: ["height$ASC", "lastName$ASC"]
          description: Define the order in which the items in a response should be returned
        - in: query
          name: firstName
          required: false
          schema:
            type: string
          description:  Filter actors by their first name
        - in: query
          name: lastName
          required: false
          schema:
            type: string
          description:  Filter actors by their last name
        - in: query
          name: birthday
          required: false
          schema:
            type: string
            format: date
          description:  Filter actors by their birthday
        - in: query
          name: height
          required: false
          schema:
            type: integer
            format: int32
          description:  Filter actors by their height
        - in: query
          name: perPage
          required: false
          schema:
            type: integer
          description: The number of items per page
        - in: query
          name: page
          required: false
          schema:
            type: integer
          description: Current oage number
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActorCollection'
    post:
      tags:
        - actors
      summary: Stores a new actor
      responses:
        '201':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActorResource'
        '422':
          description: Unprocessable content
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StoreActorRequest'
        required: true
  /actors/{actorId}:
    get:
      tags:
        - actors
      summary: Returns an actor based on ID
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActorResource'
        '404':
          description: Actor not found
    put:
      tags:
        - actors
      summary: Updates an actor
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActorResource'
        '404':
          description: Actor not found
        '422':
          description: Unprocessable content
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateActorRequest'
        required: true
    delete:
      tags:
        - actors
      summary: Deletes an actor
      responses:
        '204':
          description: Successful operation
        '404':
          description: Actor not found
    parameters:
      - $ref: '#/components/parameters/actorId'
components:
  parameters:
    actorId:
      name: actorId
      in: path
      description: ID of actor to use
      required: true
      schema:
        type: integer
  schemas:
    Actor:
      type: object
      required:
        - first_name
        - last_name
        - birthday
        - height
      properties:
        first_name:
          type: string
          maximum: 30
          example: Daniel
        last_name:
          type: string
          maximum: 30
          example: Craig
        birthday:
          type: string
          format: date
          example: '1939-06-09'
        height:
          type: integer
          format: int32
          minimum: 50
          maximum: 250
          example: 180
    ActorResource:
      required:
        - id
      properties:
        id:
          type: integer
          format: int32
          example: 1
      allOf:
        - $ref: '#/components/schemas/Actor'
        - type: object
    ActorCollection:
      type: object
      properties:
        data:
          type: array
          items:
           $ref: '#/components/schemas/ActorResource'
    StoreActorRequest:
      type: object
      allOf:
        - $ref: '#/components/schemas/Actor'
        - type: object
    UpdateActorRequest:
      type: object
      allOf:
        - $ref: '#/components/schemas/Actor'
        - type: object
