openapi: 3.0.3
info:
  version: '1.0'
  title: 'Movies API Laravel'
  description: Lab4 PAB
servers:
  - description: Laravel
    url: http://localhost:8000/api
paths:
  /movies:
    get:
      tags:
        - movies
      summary: Returns all movies
      parameters:
        - name: includeActors
          in: query
          description: Include actors in the response for each movie
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/MovieCollection'
    post:
      tags:
        - movies
      summary: Stores a new movie
      responses:
        '201':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovieResource'
        '422':
          description: Unprocessable content
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StoreMovieRequest'
        required: true
  /movies/{movieId}:
    parameters:
      - $ref: '#/components/parameters/movieId'
    get:
      tags:
        - movies
      summary: Returns a movie based on ID
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovieResource'
        '404':
          description: Movie not found
    put:
      tags:
        - movies
      summary: Updates a movie
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovieResource'
        '404':
          description: Movie not found
        '422':
          description: Unprocessable content
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateMovieRequest'
        required: true
    delete:
      tags:
        - movies
      summary: Deletes a movie
      responses:
        '204':
          description: Successful operation
        '404':
          description: Movie not found
  /movies/{movieId}/actors:
    parameters:
      - $ref: '#/components/parameters/movieId'
    get:
      tags:
        - movies-actors
      summary: Returns all actors in a given movie
      operationId: getMovieCast
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/ActorCollection'
        '404':
          description: Movie not found
    put:
      tags:
        - movies-actors
      summary: Determines a actors in a given movie
      operationId: setMovieCast
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActorCollection'
        '404':
          description: Movie not found
        '422':
          description: Unprocessable content
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SetMovieCastRequest'
  /movies/{movieId}/actors/{actorId}:
    parameters:
      - $ref: '#/components/parameters/movieId'
      - $ref: '#/components/parameters/actorId'
    put:
      tags:
        - movies-actors
      summary: Adds a actor in a given movie
      operationId: addActorToMovieCast
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActorResource'
        '404':
          description: Movie or actor not found
        '422':
          description: Unprocessable content
    delete:
      tags:
        - movies-actors
      summary: Deletes a actor in a given movie
      operationId: removeActorFromMovieCast
      responses:
        '204':
          description: Successful operation
        '404':
          description: Movie or actor not found
  /actors:
    get:
      tags:
        - actors
      summary: Returns all actors
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActorCollection'
    post:
      tags:
        - actors
      summary: Stores a new actor
      responses:
        '201':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActorResource'
        '422':
          description: Unprocessable content
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StoreActorRequest'
        required: true
  /actors/{actorId}:
    parameters:
      - $ref: '#/components/parameters/actorId'
    get:
      tags:
        - actors
      summary: Returns a actor based on ID
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActorResource'
        '404':
          description: Actor not found
    put:
      tags:
        - actors
      summary: Updates a actor
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActorResource'
        '404':
          description: Actor not found
        '422':
          description: Unprocessable content
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateActorRequest'
        required: true
    delete:
      tags:
        - actors
      summary: Deletes a actor
      responses:
        '204':
          description: Successful operation
        '404':
          description: Actor not found
components:
  parameters:
    movieId:
      name: movieId
      in: path
      description: ID of movie to use
      required: true
      schema:
        type: integer
    actorId:
      name: actorId
      in: path
      description: ID of actor to use
      required: true
      schema:
        type: integer
  schemas:
    Movie:
      type: object
      required:
        - title
        - length
        - year
        - director
      properties:
        title:
          type: string
          minLength: 2
          maxLength: 50
          example: Casino Royal
        length:
          type: integer
          format: int32
          minimum: 0
          maximum: 1300
          example: 120
        year:
          type: integer
          format: int32
          minimum: 1880
          example: 2006
        director:
          type: string
          example: Martin Campbell
    MovieResource:
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 1
        actors:
          type: array
          description: List of actors in the movie
          items:
            $ref: '#/components/schemas/ActorResource'
      allOf:
        - $ref: '#/components/schemas/Movie'
        - type: object
    MovieCollection:
      type: object
      properties:
        data:
          type: array
          items:
           $ref: '#/components/schemas/MovieResource'
    StoreMovieRequest:
      type: object
      allOf:
        - $ref: '#/components/schemas/Movie'
        - type: object
    UpdateMovieRequest:
      type: object
      allOf:
        - $ref: '#/components/schemas/Movie'
        - type: object
    SetMovieCastRequest:
      type: object
      properties:
        actorIds:
          type: array
          items:
            type: integer
          example: [1, 2, 3]
    Actor:
      type: object
      required:
        - first_name
        - last_name
        - birthday
        - height
      properties:
        first_name:
          type: string
          maximum: 30
          example: Daniel
        last_name:
          type: string
          maximum: 30
          example: Craig
        birthday:
          type: string
          format: date-time
          example: '1967-03-02'
        height:
          type: integer
          format: int32
          minimum: 0
          maximum: 250
          example: 178
    ActorResource:
      required:
        - id
      properties:
        id:
          type: integer
          format: int32
          example: 1
      allOf:
        - $ref: '#/components/schemas/Actor'
        - type: object
    ActorCollection:
      type: object
      properties:
        data:
          type: array
          items:
           $ref: '#/components/schemas/ActorResource'
    StoreActorRequest:
      type: object
      allOf:
        - $ref: '#/components/schemas/Actor'
        - type: object
    UpdateActorRequest:
      type: object
      allOf:
        - $ref: '#/components/schemas/Actor'
        - type: object
