openapi: 3.0.3
info:
  version: '1.0'
  title: 'Countries API Laravel & JWT'
  description: Lab5 PAB
servers:
  - description: Laravel
    url: http://localhost:8000/api
paths:
  /auth/login:
    post:
      tags:
        - auth
      summary: Get a JWT via given credentials
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_token'
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/credentials'
  /countries:
    get:
      tags:
        - countries
      summary: Returns all countries
      operationId: getCountries
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountryCollection'
    post:
      tags:
        - countries
      summary: Stores a new country
      operationId: storeCountry
      responses:
        '201':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountryResource'
        '422':
          description: Unprocessable content
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StoreCountryRequest'
        required: true
  /countries/{countryId}:
    get:
      tags:
        - countries
      summary: Returns a country
      operationId: getCountry
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountryResource'
        '404':
          description: Country not found
    put:
      tags:
        - countries
      summary: Updates a country
      operationId: updateCountry
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountryResource'
        '404':
          description: Country not found
        '422':
          description: Unprocessable content
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCountryRequest'
        required: true
    delete:
      tags:
        - countries
      summary: Deletes a country
      operationId: deleteCountry
      responses:
        '204':
          description: Successful operation
        '404':
          description: Country not found
    parameters:
      - $ref: '#/components/parameters/countryId'
components:
  parameters:
    countryId:
      name: countryId
      in: path
      description: ID of country to use
      required: true
      schema:
        type: integer
  schemas:
    Country:
      type: object
      required:
        - name
        - code
        - currency
        - area
        - language
      properties:
        name:
          type: string
          maxLength: 50
          example: Name
        code:
          type: string
          maxLength: 3
          example: COD
        currency:
          type: string
          maxLength: 30
          example: Currency
        area:
          type: integer
          format: int32
          minimum: 0
          example: 100000
        language:
          type: string
          maxLength: 50
          example: language
    CountryResource:
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 1
      allOf:
        - $ref: '#/components/schemas/Country'
        - type: object
    CountryCollection:
      type: object
      properties:
        data:
          type: array
          items:
           $ref: '#/components/schemas/CountryResource'
    StoreCountryRequest:
      type: object
      allOf:
        - $ref: '#/components/schemas/Country'
        - type: object
    UpdateCountryRequest:
      type: object
      allOf:
        - $ref: '#/components/schemas/Country'
        - type: object
    credentials:
      type: object
      required:
      - email
      - password
      properties:
        email:
          type: string
          format: email
          example: user@email.com
        password:
          type: string
          example: pass
    access_token:
      type: object
      properties:
        access_token:
          type: string
          example: header.payload.signature
        token_type:
          type: string
          example: bearer
        expires_in:
          type: integer
          example: 60
