openapi: 3.0.3
info:
  version: '1.0'
  title: Countries API Laravel
  description: Lab2 PAB
servers:
  - description: Laravel
    url: 'http://localhost:8000/api'
paths:
  /countries:
    get:
      tags:
        - countries
      summary: Returns all countries
      responses:
        200:
          description: All countries
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountryCollection'
    post:
      tags:
        - countries
      summary: Creates country
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StoreCountryRequest'
      responses:
        201:
          description: Country created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountryResource'
        422:
          description: Unprocessable entity
  /countries/{countryId}:
    get:
      tags:
        - countries
      summary: Returns one country
      parameters:
        - $ref: '#/components/parameters/countryId'
      responses:
        200:
          description: One country
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountryResource'
        404:
          description: Country not found
    put:
      tags:
        - countries
      summary: Updates country
      parameters:
        - $ref: '#/components/parameters/countryId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCountryRequest'
      responses:
        200:
          description: Country updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountryResource'
        404:
          description: Country not found
        422:
          description: Unprocessable entity
    delete:
      tags:
        - countries
      summary: Deletes Country
      parameters:
        - $ref: '#/components/parameters/countryId'
      responses:
        204:
          description: Country deleted
        404:
          description: Country not found
components:
  parameters:
    countryId:
      name: countryId
      in: path
      description: ID of country to use
      required: true
      schema:
        type: integer
  schemas:
    Country:
      type: object
      description: Information about one country
      required:
        - name
        - code
        - area
        - language
      properties:
        id:
          type: integer
          format: int32
          default: 1
        name:
          type: string
          maxLength: 50
          default: Name
        code:
          type: string
          maxLength: 3
          default: COD
        currency:
          type: string
          maxLength: 30
          default: currency
        area:
          type: integer
          minimum: 0
          default: 100000
        language:
          type: string
          maxLength: 50
          default: language
    CountryResource:
      allOf:
        - $ref: '#/components/schemas/Country'
        - type: object
          description: Resource wrapper for one country
    CountryCollection:
      type: array
      items:
        $ref: '#/components/schemas/CountryResource'
      description: Resource wrapper for countries
    StoreCountryRequest:
      allOf:
        - $ref: '#/components/schemas/Country'
        - type: object
          description: Information about one country used to add a new country
          required:
            - name
            - code
            - area
            - language
          properties:
            id:
              type: integer
              format: int32
              readOnly: true
    UpdateCountryRequest:
      allOf:
        - $ref: '#/components/schemas/StoreCountryRequest'
        - type: object
          description: Information about one country used to edit an existing country
